version: "3.7"

# redis-n localhost-g redis bolgoh
# mysqldb-g nemeh
# password nemeh

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-tier
    expose:
      - 6379
    ports:
      - 6379:6379
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - app-tier
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: gql_test

    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mysqldb
      - redis
    networks:
      - app-tier

volumes:
  mysql-data:
